# TCL File Generated by Component Editor 8.0
# Wed Oct 26 23:44:54 CEST 2022
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avalon_pwm "avalon_pwm" v1.0
# | null 2022.10.26.23:44:54
# | 
# | 
# | D:/BER_MED/TP3/Lab_1_SoPC_restored/PWM_Device/avalon_pwm.vhd
# | 
# |    ./avalon_pwm.vhd syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module avalon_pwm
# | 
set_module_property NAME avalon_pwm
set_module_property VERSION 1.0
set_module_property GROUP "Peripherals/Microcontroller Peripherals"
set_module_property DISPLAY_NAME avalon_pwm
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.numeric_std.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE avalon_pwm.vhd
set_module_property TOP_LEVEL_HDL_MODULE avalon_pwm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file avalon_pwm.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 minimumUninterruptedRunLength 1
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 addressSpan 8
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 printableDevice false

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_reset

add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 address address Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point global_signal
# | 
add_interface global_signal conduit end

set_interface_property global_signal ASSOCIATED_CLOCK clock_reset

add_interface_port global_signal out_port export Output 26
# | 
# +-----------------------------------
